### ISSUE TITLE
Question: Terrain Vertex color shader...

### ISSUE THREAD

**Issue by Gusher** [puchik/godot-extras#4]
Is it possible to save the splatmap after finishing up blending?

**Comment by puchik** [comment]
You mean using the blending sliders to make a custom splat map? Maybe for use somewhere else?

If so.... hmmm that's not an available feature, but you _could_ do your blending, leave everything as it is, replace your textures with flat colours (rgb), turn off shading so it's all equally lit and even, then take a screenshot from orthogonal camera view and use that as a splat map... don't know how well it would work with curved surfaces though.

**Comment by Gusher** [comment]
For example, Zylann's terrain plugin creates a copy of the splatmap in the project folder and was wondering if your addon does that too, that can further work with it with external tools like photoshop... am still trying figure out how to setup.... do you have a youtube video showing how to setup? Thanks...

**Comment by puchik** [comment]
Ahh but it's not a plugin, just a shader. If you're referring to how I did the painting in the video, that's [VPainter](https://github.com/tomankirilov/VPainter) which paints to the vertices in the model (which you can't save as a splat map). Otherwise, the shader can't create any mapping, it can only use existing splat maps or vertex colour.

It will work with photoshop in the sense that you can use images made in photoshop as a splat map.

Set up just involves assigning a ShaderMaterial to some mesh and filling in the parameters. I might make a video eventually but it should be relatively straight forward and there are some instructions in the [README](https://github.com/puchik/godot-extras/tree/master/visual/terrain-vertex-shader).

**Comment by Gusher** [comment]
Thanks for explaining, am just a beginner of GODOT, exploring addons, would be great to make a short video guide for the newcomers to GODOT... thanks!

**Comment by puchik** [comment]
No problem! I'll consider it, but it should not be too complicated to use the instructions once you read the Godot guides here:
https://docs.godotengine.org/en/stable/tutorials/shading/shader_materials.html 
https://docs.godotengine.org/en/stable/tutorials/shading/shader_materials.html
Good luck!
